/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class layers_continuum_solvers_EquilibriumPetscSolver */

#ifndef _Included_layers_continuum_solvers_EquilibriumPetscSolver
#define _Included_layers_continuum_solvers_EquilibriumPetscSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     layers_continuum_solvers_EquilibriumPetscSolver
 * Method:    solve
 * Signature: (I[I[[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_layers_continuum_solvers_EquilibriumPetscSolver_solve
  (JNIEnv *, jobject, jint, jintArray, jobjectArray, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
